// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	entity "github.com/mehgokalp/vendor-rhino/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// CurrencyRepository is an autogenerated mock type for the CurrencyRepository type
type CurrencyRepository struct {
	mock.Mock
}

// FindByCode provides a mock function with given fields: code
func (_m *CurrencyRepository) FindByCode(code string) *entity.Currency {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *entity.Currency
	if rf, ok := ret.Get(0).(func(string) *entity.Currency); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Currency)
		}
	}

	return r0
}

// NewCurrencyRepositoryInterface creates a new instance of CurrencyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCurrencyRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CurrencyRepository {
	mock := &CurrencyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
