language: go

matrix:
  fast_finish: true
  include:
    - go: "1.13"
  allow_failures:
    - go: master

go_import_path: github.com/MehGokalp/vendor-rhino

services:
  - mysql

script:
#  - go test -v ./...
  - bash ./scripts/gofmt.sh
  - bash ./scripts/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
