name: vendor-rhino-ci
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/github.com/mehgokalp/vendor-rhino
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      - run: go test -coverpkg=./... -race -failfast -p 1 -covermode=atomic -coverprofile=coverage.out -v ./...
        working-directory: go/src/github.com/mehgokalp/vendor-rhino
        env:
          GOPATH: "/home/runner/work/vendor-rhino/vendor-rhino/go"
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.1
      - run: golangci-lint run
